### ISSUE TITLE
Issue connecting to git repository on IBM iSeries with ssh

### ISSUE THREAD

**Issue by kraisor-kheaa** [IBM/ibmi-oss-issues#25]
I'm able to access the repository if I use the file:// connect method via a mapped drive to the iSeries, but when I try to connect via SSH, I get the following error:
org.eclipse.jgit.api.errors.TransportException: ssh://kraisor@sysname/home/KRAISOR/gitrepo/: bsh: git-upload-pack: not found

	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:221)

	at org.eclipse.jgit.api.LsRemoteCommand.call(LsRemoteCommand.java:159)

	at org.eclipse.egit.core.op.ListRemoteOperation.run(ListRemoteOperation.java:100)

	at org.eclipse.egit.ui.internal.clone.SourceBranchPage$8.run(SourceBranchPage.java:341)

	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException: ssh://kraisor@sysname/home/KRAISOR/gitrepo/: bsh: git-upload-pack: not found

	at org.eclipse.jgit.transport.TransportGitSsh.cleanNotFound(TransportGitSsh.java:209)

	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:290)

	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:162)

	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:198)

	... 4 more

I have gone through and setup a system environment variable for PASE that points to the git bin folder

PASE_PATH                   '/QopenSys/usr/bin:/QopenSys/pkgs/bin'

The error above is from my eclipse log in RDi, but the actual pop up error message is the image I attached

Any help would be appreciated
![giterror](https://user-images.githubusercontent.com/106983457/196164872-d74598ac-371c-4487-8756-ec9b8f28271a.png)

**Comment by kadler** [comment]
You are trying to connect to an git repo hosted on an IBM i system from your local Eclipse environment?

**Comment by kraisor-kheaa** [comment]
I figured it out.  I was still using bsh and not bash environment.  Once I changed that and used a .bashrc file to set the path, everything worked.
